import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import UpperNav from "@/container/upperNav";
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";
import Sponsors from "@/container/Sponsors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ekkhuny Somoy",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-gray-900`}
      >
        <UpperNav />
        <Navbar />
        {children}
        <Sponsors />
        <Footer />
      </body>
    </html>
  );
}
